apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: aiops
  namespace: seldon
spec:
  name: aiops
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: tybalex/pcamodel
          name: pca
          env:
          - name: NATS_SERVER_URL
            value: "nats://nats_client:VfU6TcAl9x@nats-client.default.svc:4222"
          - name: MINIO_ACCESS_KEY
            value: "myaccesskey"
          - name: MINIO_SECRET_KEY
            value: "mysecretkey"
          resources:
            requests:
              memory: "2000Mi"
    graph:
      name: pca
      type: MODEL
    name: default
    replicas: 1
